python-mode/python-mode

- pymode/rope.py
Unless someone wants to autoimport all of the standard modules, removing this multiprocessing process shouldn't result in any performance loss. I did not find any difference and, as far as I can tell, the python-rope/ropevim implementation does not use multiprocessing either.
If someone still really wants multiprocessing in this instance, there are some other possible workarounds so as to not leave Windows users out in the cold, though I haven't thought of any that aren't ugly. As far as I can tell, the rope objects being used are not pickleable, and there's not much to be done there.
> Remove call to multiprocessing. Fixes issue #422.

- autoload/pymode/folding.vim
Some docstrings/code parts use line continuation with zero whitespace on the
following line. In this case we should accept the previous lines indentation
instead of forcing the indentation to be zero.
> Don't force indentation to be 0 for lines not starting with whitespace

- pymode/run.py
According to PEP263, the first or second line must match the regular expression "coding[:=]\s*([-\w.]+)".
> Fix #482, (PEP 263 Python Source Code Encodings)

- pymode/rope.py
* (Temporarily) drops passing of `task_handle`.
More refactoring is in order to fully interface for all the things that rope is capable of.
Resolves #494
> rope: correct refactoring function calls

- autoload/pymode/folding.vim
According to [pep257](https://www.python.org/dev/peps/pep-0257/#multi-line-docstrings), "The summary line may be on the same line as the opening quotes or on the next line." This PR will always show the summary line in a fold even if it is on the same line as the opening quotes.
> Don't skip a line when the first docstring contains text

- autoload/pymode/folding.vim
Simply checks whether the next line is more indented than the line
matching def_regex and if it's not don't increase the fold level.
Avoids an issue where 
```python
def rev(x): return reverse(x)
if something:
def rev(x): return x
```
gets folded to
```python
def rev(x): return reverse(x)
```
not showing the rest of the code.
> Don't fold single line def

- doc/pymode.txt
I'm new to python-mode and reading the help, it looked to me like the details of `let g:python_mode` help description were out of place.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/klen/python-mode/542)
> fix placement of pymode_options help description

- README.rst
For people behind a proxy server it is difficult to 'git clone' using
'git:'.  While 'https:' is universally usable.
> Use 'https:' instead of 'git:' in documentation

- doc/pymode.txt
Hello,  I noticed an unwanted ')' in documentation.
> removing misstype

- syntax/python.vim
Comments are allowed in function argument and class parameter lists so they should be highlighted correctly. Git's markup language gets it half right:
```python
class Foo(a,  # blah
b,  # blah
):
pass
def bar(a=None,  # blah
b=0,     # blah
):
pass
```
For a prominent example of a function with comments in the argument list, see `matplotlib.figure.Figure`:
```python
class Figure(Artist):
"""
...
"""
def __init__(self,
figsize=None,  # defaults to rc figure.figsize
dpi=None,  # defaults to rc figure.dpi
facecolor=None,  # defaults to rc figure.facecolor
edgecolor=None,  # defaults to rc figure.edgecolor
linewidth=0.0,  # the default linewidth of the frame
frameon=None,  # whether or not to draw the figure frame
subplotpars=None,  # default to rc
tight_layout=None,  # default to rc …
```
> Highlight comments inside class/function arg lists

- autoload/pymode/doc.vim
- plugin/pymode.vim
Added an option to display Python docs in vertical windows.
To enable the option, user needs to modify her .vimrc file as follows:
```vim
let pymode_doc_vertical = 1
```
> Add Python documentation vertical display option

- autoload/pymode.vim
* Added condition to the trim function itself.
> g:pymode_trim_whitespaces = 0 was ignored.

- autoload/pymode/folding.vim
This change caused a regression in folding: https://github.com/klen/python-mode/pull/534
If there is a blank line between a `class`/`def` statement, a fold won't be created. For example, the following folds into one line (`class Foo(object):`) before the change but not after:
```python
class Foo(object):
"""Description."""
def __init__(self):
pass
```
> Fix folding after blank line in class/def

- autoload/pymode/indent.vim
Doctests should be treated the same as strings/comments when searching for open pairs.
Before this change:
```python
class Foo:
"""
>>> print '{ { }'
{ { }
"""
def __init__(self):
pass
```
After this change (correct indent of 'pass'):
```python
class Foo:
"""
>>> print '{ { }'
{ { }
"""
def __init__(self):
pass
```
> Skip doctest regions when searching for open pairs

- doc/pymode.txt
A few lines in the docs were out of order, specifically with regard to what setting pymode_options to 1 does.
> Removed ambiguity in doc/pymode.txt related to pymode_options defaults

- autoload/pymode.vim
This avoids accessing the `b:python_modified` var, which under some circumstances won't be set, which results in the following error:
Error detected while processing function pymode#buffer_post_write:
line    2:
E121: Undefined variable: b:pymode_modified
E15: Invalid expression: b:pymode_modified && g:pymode_rope_regenerate_on_write
**Note:** this does not address the core issue with why `b:pymode_modified` is unset in the first place, but this avoids that being a problem if `g:python_rope_regenerate_on_write` is not wanted anyway.
> Fix `Undefined variable: b:pymode_modified` error when regeneration of rope project isn't wanted

- pymode/lint.py
The `check_path` function in the new version of pylama does an `os.path.exists` check on the name of the buffer before it will check it. This prevents the linter from running when editing a new file that hasn't been saved yet or in a scratch buffer. The old version of `check_path` didn't do anything extra that we need so I suggest calling `run` on the code directly.
> Fix running lint on buffer without existing file

- pymode/libs3/rope/base/fscommands.py
Make the encoding detection regexp less strict so that it will detect the encoding of files
that do not have a space between the "coding:" statement and the encoding value.
Example: https://github.com/dateutil/dateutil/blob/master/dateutil/parser.py
> Make encoding regexp less strict

- autoload/pymode/virtualenv.vim
- doc/pymode.txt
- pymode/virtualenv.py
- t/virtualenv.vim
This will allow you to specify an absolute path when activating a virtual environment. This can be useful for people using `virtualenvwrapper` where all of your environments are typically kept in some folder under your home directory.
Before:
```
:PymodeVirtualenv "/Users/matt/venv/myenv"
[Pymode]: error: [Errno 2] No such file or directory: '/Users/matt/code/Users/matt/venv/myvenv'
```
After:
```
:PymodeVirtualenv "/Users/matt/venv/myenv"
[Pymode] Activate virtualenv: /Users/matt/venv/myenv
```
It also adds a rather dumb unit test for the virtualenv command. My vim-script-noobness has left me unable to make it smarter. I added a TODO for someone that knows what they are doing to hopefully help.
> Absolute paths for virtualenv activation

- autoload/pymode/folding.vim
Cache the results of Is_opening_folding once per change so it doesn't loop over the same lines multiple times unnecessarily. For autopep8.py for example, this reduced folding time from >10 seconds to near instantaneous.
> Make folding much faster in some cases

- autoload/pymode/folding.vim
pymode folding recognizes docstring styles (''', """) and the unicode u, U prefix (u''', u""") but does not recognize a raw prefix. This pull request adds this functionality.
> Updated docstring regex to allow folding of raw python strings

- README.rst
After migrating this repo from `klen` to `python-mode` account, Travis build status indicator ceased to work.
This commit fixes that, together with streamlining other links.
> Update owner name in links in readme

- syntax/python.vim
Python 3.6 introduced [PEP 515](https://www.python.org/dev/peps/pep-0515/) which allows underscore character (`_`) in numeric literals. This commit is intended to properly highlight such literals.
> Do support underscore in numbers, pep515 (py3.6)

- README.rst
Better to redirect to Stackoverflow as very few people log into the slack channel to reply.
> Slack now has tonnes of unanswered question

- AUTHORS
- plugin/pymode.vim
On the documentation (`README.md` and `doc/pymode.txt`) `pep257` is described as a possible option as a linter, but on the source code comment it was not, I'm just setting it over there to make sure anyone reading the source code knows their options. =)
> Add pep257 linter option on source comment

- .gitmodules
The submodule URL for `PyCQA/pydocstyle` was incorrect so doing `git clone --recursive ...` failed with the following error:
```
Cloning into '/Users/makram/.vim/bundle/python-mode/submodules/pydocstyle'...
ERROR: Repository not found.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'https://github.com/PyCQA/pydocstyle/' into submodule path '/Users/makram/.vim/bundle/python-mode/submodules/pydocstyle' failed
Failed to clone 'submodules/pydocstyle'. Retry scheduled
...
Cloning into '/Users/makram/.vim/bundle/python-mode/submodules/pydocstyle'...
ERROR: Repository not found.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists. …
```
> Fix pydocstyle submodule URL

- pymode/rope.py
Fix for #728 . As noted by @pieterdd and @soulomoon calling autoimport results in AttributeError. Rope ImportTools expect to get Project object as input argument to init function not PyCore object.
> Fix #728, pass rope project to ImportTools init

- AUTHORS
- readme.md
Fixes #864 
Consider adding a note about using the `development` branch in case the user wants to install using another git-based vim plugin manager.
> Add proper vim-plug installation instructions
